// Constants
import { E_APP_FONTS, E_APP_COLORS } from '@/features/app/constants'

const styledComponentsTheme = {
	fontFamily: E_APP_FONTS.FONT_FAMILY,
	fonts: {
		FONT_FAMILY: E_APP_FONTS.FONT_FAMILY,
		BLACK: E_APP_FONTS.BLACK,
		BLACK_ITALIC: E_APP_FONTS.BLACK_ITALIC,
		BOLD: E_APP_FONTS.BOLD,
		BOLD_ITALIC: E_APP_FONTS.BOLD_ITALIC,
		EXTRA_BOLD: E_APP_FONTS.EXTRA_BOLD,
		EXTRA_BOLD_ITALIC: E_APP_FONTS.EXTRA_BOLD_ITALIC,
		EXTRA_LIGHT: E_APP_FONTS.EXTRA_LIGHT,
		EXTRA_LIGHT_ITALIC: E_APP_FONTS.EXTRA_LIGHT_ITALIC,
		ITALIC: E_APP_FONTS.ITALIC,
		LIGHT: E_APP_FONTS.LIGHT,
		LIGHT_ITALIC: E_APP_FONTS.LIGHT_ITALIC,
		MEDIUM: E_APP_FONTS.MEDIUM,
		MEDIUM_ITALIC: E_APP_FONTS.MEDIUM_ITALIC,
		REGULAR: E_APP_FONTS.REGULAR,
		SEMI_BOLD: E_APP_FONTS.SEMI_BOLD,
		SEMI_BOLD_ITALIC: E_APP_FONTS.SEMI_BOLD_ITALIC,
		THIN: E_APP_FONTS.THIN,
		THIN_ITALIC: E_APP_FONTS.THIN_ITALIC
	},
	colors: {
		primary: E_APP_COLORS.PRIMARY
	}
}

export { styledComponentsTheme }
